### ISSUE TITLE
Changing dnsConfig (specifically ndots) in routed namespace 

### ISSUE THREAD

**Issue by mergwyn** [angelnu/pod-gateway#26]
# Details

**What steps did you take and what happened:**

I am using pod-gateway in a microk8s cluster (which includes calico) deployed using the helm chart from: [https://github.com/angelnu/helm-charts/tree/main/charts/apps/pod-gateway](https://github.com/angelnu/helm-charts/tree/main/charts/apps/pod-gateway) following the instructions on: [https://docs.k8s-at-home.com/guides/pod-gateway/](https://docs.k8s-at-home.com/guides/pod-gateway/). The test deployment works correctly apart from DNS resolution issues which can be addressed by manually changing ndots to 1.

When deploying other containers such as xteve I attempt to change ndots value using dnsConfig to avoid the same dns resolution errors:
```
dnsConfig:
  options:
  - name: ndots
    value: "1"
```

Whilst this works as expected in a non-routed namespace when using in a routed namespace the ndots remains set to 5. I suspect, but don't know how to debug, that there is some interaction between the prod-gateway client scripts an container startup that is preventing these settings from being applied.

**What did you expect to happen:**

I expected the dnsConfig settings to be observed or for there to be another way to change the setting.

This is what happens in the test deployment:
```
$ kubectl exec -ti -n media-vpn deploy/terminal -- sh
Defaulted container "alpine" out of: alpine, gateway-sidecar, gateway-init (init)
/ # ping google.com
ping: bad address 'google.com'
/ # ping google.com.
PING google.com. (142.250.200.14): 56 data bytes
64 bytes from 142.250.200.14: seq=0 ttl=115 time=70.194 ms
64 bytes from 142.250.200.14: seq=1 ttl=115 time=60.746 ms
^C
--- google.com. ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 55.856/63.576/70.194 ms
/ # cat /etc/resolv.conf 
search media-vpn.svc.cluster.local svc.cluster.local cluster.local theclarkhome.com local
nameserver 172.16.0.1
options ndots:5
/ # vi /etc/resolv.conf 
/ # cat /etc/resolv.conf 
search media-vpn.svc.cluster.local svc.cluster.local cluster.local theclarkhome.com local
nameserver 172.16.0.1
options ndots:1
/ # ping google.com
PING google.com (142.250.200.14): 56 data bytes
64 bytes from 142.250.200.14: seq=0 ttl=115 time=58.131 ms
64 bytes from 142.250.200.14: seq=1 ttl=115 time=43.994 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 43.994/51.062/58.131 ms
```

My pod-gateway values.yaml:
```
---
image:
  repository: ghcr.io/mergwyn/pod-gateway
  pullPolicy: Always
  tag: dev

routed_namespaces:
  - media-vpn

settings:
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8" #172.16.0.0/24"
  VPN_LOCAL_CIDRS: "10.0.0.0/8" #172.16.0.0/24"
  DNS_LOCAL_CIDRS: "local"
  VPN_INTERFACE: "tun0"
  IPTABLES_NFT: "yes"
  VPN_TRAFFIC_PORT: 1194
  VPN_BLOCK_OTHER_TRAFFIC: false
  GATEWAY_ENABLE_DNSSEC: false

dnsConfig:
  options:
    - name: ndots
      value: "1"

addons:
  vpn:
    # -- Enable the VPN if you want to route through a VPN.
    # You might also want to set VPN_BLOCK_OTHER_TRAFFIC to true
    # for extra safeness in case the VPN does connect
    enabled: true
    type: gluetun
    networkPolicy:
      enabled: false
    env:
      TZ: Europe/London
      VPN_SERVICE_PROVIDER: privatevpn
      VPN_TYPE: openvpn
      OPENVPN_USER: *********
      OPENVPN_PASSWORD: *************
      SERVER_CITIES: Manchester
      OPENVPN_VERBOSITY: 1
      VPN_INTERFACE: "tun0"
      FIREWALL: "off"
      DOT: "off"
      VPN_BLOCK_OTHER_TRAFFIC: "true"
      FIREWALL_VPN_INPUT_PORTS: 64709
      VPN_ENDPOINT_PORT: 1194
```

**Additional Information:**

Hopefully,  you will be able to point me in the right direction to work out how to fix this issue. Please let me know if there is any additional information I can provide to help.
