### ISSUE TITLE
subnet mask /16 is not supported and VPN interface tun0 not created

### ISSUE THREAD

**Issue by grapemix** [angelnu/pod-gateway#50]
# Details

**What steps did you take and what happened:**
At the beginning, I found out that I cannot ping any ip or domains at the pod-gateway. After diving in, I found out that the VPN tun0 has not been created. Then I realized only subnet mask /24 is supported, not /16. I tried to pass a /16 subnet mask to the pod, but the pod cannot even ping my router.

The reason for using /16 subnet mask is because I want to have a future-proof network which supports VLAN and iOT devices. Although iOT devices don't need VPN, but they do need to connect to the gateway of my homelab cluster. For network security reasons, it is best to split the network via VLAN and hence /16 subnet mask is used. I hope my usecase make sense for you to support /16 subnet mask.

Please let me know anything I can help. Thanks a lot.
**What did you expect to happen:**
1. /16 subnet mask is supported
2. tun0 is created
3. I can ping my router and domains in the Internet.

**Anything else you would like to add:**
I am not sure my case is the same as https://github.com/angelnu/pod-gateway/issues/12.

**Additional Information:**
Here is the values I used. I also created another helm release for the gluetun alone to make sure my settings for gluetun worked as expected.

```
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.34.3@sha256:55f6c5b9cd2646b7d3f95c48f2d35e9e01fefa5d927f8636392e104f6d86639b
        env:
          - name: TZ
            value: ${TIMEZONE}
          - name: VPN_SERVICE_PROVIDER
            value: private internet access
          - name: SERVER_REGIONS
            value: Netherlands
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: VPN_INTERFACE
            value: &VPN_INTERFACE tun0
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 60s
          - name: LOG_LEVEL
            value: debug
        envFrom:
          - secretRef:
              name: ${APP}-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 50M
    DNS: 172.70.5.81
    podAnnotations:
      # network policy and generated config
      secret.reloader.stakater.com/reload: ${APP}-secret
    settings:
      VPN_TRAFFIC_PORT: ${VPN_TRAFFIC_PORT}
      VPN_LOCAL_CIDRS: 10.0.0.0/8 172.16.0.0/12 172.70.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 172.16.0.0/12 172.70.0.0/16
      #VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: *VPN_INTERFACE
      VXLAN_ID: 56
      VXLAN_IP_NETWORK: 172.70
```
